// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqIY3b76jZdj-oReGKNlJ36pHsOSR64E',
    appId: '1:667710416901:web:2f3941f69cf26c8421946c',
    messagingSenderId: '667710416901',
    projectId: 'survival-photopin',
    authDomain: 'survival-photopin.firebaseapp.com',
    storageBucket: 'survival-photopin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLc0onJSTvkea3d6HDPJKNkfotHyhK6UE',
    appId: '1:667710416901:android:76a1e45ac2d5131621946c',
    messagingSenderId: '667710416901',
    projectId: 'survival-photopin',
    storageBucket: 'survival-photopin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsJ8utVAMhW6IoUQfK_tVRZ9hlZCDm_s',
    appId: '1:667710416901:ios:ae8b191194c0814021946c',
    messagingSenderId: '667710416901',
    projectId: 'survival-photopin',
    storageBucket: 'survival-photopin.firebasestorage.app',
    androidClientId:
        '667710416901-2l3b417vneek7n70nllr8045rgcrk7k0.apps.googleusercontent.com',
    iosClientId:
        '667710416901-g33blgi7326eo4fq03a6f4qrri3vp1gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.photopin',
  );
}
