name: Flutter

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # PR 브랜치의 현재 상태를 checkout
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3

      - name: Install dependencies
        run: flutter pub get

      - name: Format project source
        run: dart format --set-exit-if-changed .

<<<<<<< HEAD
=======
      - name: analyze project source
        run: flutter analyze

>>>>>>> origin/dev
      - name: Run tests
        run: flutter test -r github
